import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="flex justify-between border-b px-6 py-3">
      <span className="font-bold">RevoShop</span>
      <nav className="flex gap-4 text-sm">
        <Link href="/">Home</Link>
        <Link href="/products">Products</Link>
        <a href="/categories">Visit Our Other Site</a>
        <a href="/orders">Orders</a>
      </nav>
    </header>
  );
}

function Footer() {
  // TODO: a centered footer bar reading "Footer — app/layout.tsx"
  return (
    <footer className="border-t px-6 py-3 text-center text-sm text-gray-400">
      Footer — app/layout.tsx
    </footer>
  );
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* <Header /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         {children}
//       </body>
//     </html>
//   );
// }

// function Header() {
//   return (
//     <header className="flex justify-between items-center border-b px-6 py-3">
//       <span className="font-bold text-lg">RevoShop</span>
//       <nav className="flex gap-4 text-sm text-gray-600">
//         <span>Home</span><span className="font-semibold text-black">Products</span>
//         <span>Categories</span><span>Orders</span>
//       </nav>
//     </header>
//   );
// }

// function Footer() {
//   return <footer className="border-t px-6 py-3 text-center text-gray-400 text-sm">Footer — app/layout.tsx</footer>;
// }